### ISSUE TITLE
possible use rpi inegrated ble?

### ISSUE THREAD

**Issue by dreamer2** [v1ack/smartLightConnector#1]

**Comment by v1ack** [comment]
Yes, I use it on my raspberry pi 4

**Comment by dreamer2** [comment]
you use debian, so Home Assistant Operating System not supported/tested yet

**Comment by v1ack** [comment]
To add integration you need a running docker container with this app (take a look at docker compose)
Now I'm working on new ha integration which will work without additional requirements
