### ISSUE TITLE
Проблема с подключением интеграции lelight

### ISSUE THREAD

**Issue by WizarD-3354** [v1ack/smartLightConnector#2]
![image](https://user-images.githubusercontent.com/115119438/196970931-3df020cc-8e43-430b-bfb6-84f2260335e8.png)

@v1ack 
**Выдает данную ошибку при попытке добавить интеграцию.** 
Пробовал в конфиге дописать "Lelight:"

![image](https://user-images.githubusercontent.com/115119438/196971211-11b82263-65cc-4b74-8816-a9474d5dbe2e.png)

Теперь HA ругается на новый конфиг... 

![image](https://user-images.githubusercontent.com/115119438/196971342-4a736d0d-bbaa-4ca8-b5a0-202cf6aa4002.png)

Пробовал переустановить и обновить Dbus и Dbus_next, результатов не дало. 
**HA установлен на OrangePi на системе Linux Ubuntu**

Подскажите как решить данную проблему?

**Comment by v1ack** [comment]
Исправлено в 0.1.1 https://github.com/v1ack/lelight/
Настройка интеграции производится через интерфейс, а не конфиг
